# fly.toml app configuration file generated for ultimate-disco on 2023-09-22T14:38:07-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ultimate-disco"
primary_region = "den"
kill_timeout = 120

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]
  [build.args]
    BP_KEEP_FILES = "css/*:js/*:html/*:node_modules/*:img/*"

[env]
  ENV = "PROD"
  PORT = "8080"
  BOSS_EMAIL = "Onsi Fakhouri <onsijoe@gmail.com>"
  SATURDAY_DISCO_EMAIL = "Saturday Disco <saturday-disco@sedenverultimate.net>"
  SATURDAY_DISCO_LIST = "saturday-sedenverultimate@googlegroups.com"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ["app"]
