# fly.toml app configuration file generated for ultimate-disco on 2023-09-22T14:38:07-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ultimate-disco"
primary_region = "den"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]
  [build.args]
    BP_KEEP_FILES = "css/*:js/*:html/*:node_modules/*"

[env]
  ENV = "PROD"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
